---
title: 'Certificación'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- ¿Cómo accedo al certificado de NASA Open Science 101?

- ¿Cómo accedo al certificado de MetaDocencia Herramientas de Ciencia Abierta?



::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Identificar los requisitos mínimos para acceder a los certificados.


::::::::::::::::::::::::::::::::::::::::::::::::


::::::::::::::::::::::::::::::::: callout

Este es un aviso o callout

:::::::::::::::::::::::::::::::::






::::::::::::::::::::::::::::::::::::: keypoints 

- El aprendizaje es más efectivo cuando las personas participan activamente, usando, explicando y poniendo a prueba lo que aprenden, en lugar de solo recibir información.

- Las estrategias de aprendizaje activo ayudan a que la información se codifique mejor en la memoria a largo plazo y sea más fácil de recuperar y transferir.

- Patrones como PRIMM muestran cómo estructurar actividades que guían progresivamente desde la comprensión hacia la creación, reduciendo la carga cognitiva.

- Incorporar estrategias basadas en evidencia y promover la metacognición permite que estudiantes y docentes tomen decisiones más conscientes sobre cómo aprender mejor.

::::::::::::::::::::::::::::::::::::::::::::::::
