---
title: 'Encuentro 1 - Herramientas de Ciencia Abierta'
teaching: 10
exercises: 2
---

El encuentro 1 es una introducción en la que se presentan los conceptos clave del curso, se plantea como propósito adicional romper el hielo entre participantes. A partir de los contenidos que plantea el curso de [NASA Open Science 101](https://stemgateway.nasa.gov/s/course-offering/a0BSJ0000049ih3/open-science-101), te proponemos desarrollar una clase virtual, trabajando de forma colaborativa para seleccionar, priorizar y ajustar en base a nuestra experiencia y nuestra mirada latinoamericana los contenidos del primer módulo de NASA TOPS.

## Objetivos del Encuentro 1
1. Conocer a las personas participantes de la cohorte y promover la participación y la comunicación entre sí a partir de sus propias experiencias, trayectorias y necesidades.
2. Proponer una definición de Ciencia Abierta a partir de su ethos, principios y valores.
4. Reconocer los desafíos que implican las prácticas de Ciencia Abierta en el marco de su aplicación en nuestro contexto.
5. Reflexionar sobre los miedos que suscita la aplicación de las prácticas de Ciencia Abierta y construir colaborativamente estrategias para mitigarlos. 


## Cronograma
|  Hora | Actividad | Duración |
| ---:  | :----------- | :----------- |
|-00:15 | Tiempo previo para conectarse | 
|00:00 | Bienvenida e información general | 15 mins |
|00:15 | **Ejercicio 1.** Presentación de las personas | 3 mins |
|00:18 | Bloque 1. ¿Qué es la Ciencia Abierta?   | 10 mins |
|00:28 | **Ejercicio 2.** Breve encuesta | 3 mins |
|00:31 | Desafíos de la Ciencia Abierta  | 10 mins |
|00:41 | Preocupaciones y formas de mitigarlas | 10 mins |
|00:56 | **Ejercicio 3.** Ejercicio en salas de grupo | 14 mins |
|01:10 | *Pausa* | 10 mins |
|01:20 | Bloque 2. Principios FAIR | 15 mins |
|01:35 | **Ejercicio 4.** Breve encuesta | 3 mins |
|01:40 | Próximos pasos | 10 mins |
|01:50 | Encuesta anónima | 5 mins |
|01:55 | Evaluación de contenidos para la certificación | 15 mins |
|02:10 | Cierre | 5 mins |

## Materiales

- Presentación: []
  
### ¡Sírvete sin culpa!
Nuestros materiales están disponibles de forma gratuita bajo esta [licencia](https://creativecommons.org/licenses/by/4.0/deed.es). Es decir, puedes reusar o editar cualquier material que aparece acá, lo único que pedimos a cambio es que cuando tomes material de acá, incluyas una referencia a esta página web.
